version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: 'confluentinc/cp-kafka:6.2.0'
    environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     KAFKA_ADVERTISED_HOST_NAME: kafka:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"
      - "9101:9101"
    depends_on:
      - zookeeper
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  writer:
    build: ./writer
    restart: always
    environment:
      KAFKA_URL: kafka:29092
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
      - mongo-express
      - kafka
  #     - zookeeper
  scanner:
    build: ./ping
    restart: always
    environment:
      KAFKA_URL: kafka:9092
    depends_on:
      - mongo
      - mongo-express
      - kafka
      - zookeeper
  

    
  # writer:
  #   build: ./writer
  #   environment:
  #     KAFKA_URL: kafka:9092
  #     MONGODB_URL: mongodb://root:example@mongo:27017/